options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run','deploy','cloudrun-cicd',
         '--source','.',
         '--region','us-central1',
         '--allow-unauthenticated']
